### ISSUE TITLE
TSS.MSR for UWP

### ISSUE THREAD

**Issue by RutujaWanjari** [Microsoft/TSS.MSR#1]
Hello Team,

I am getting TcpTpmDevice error while using one of your samples of .net () in UWP project.
Steps followed - 1. Copied all .cs files from TSS.NET to TSS.UWP
                          2. Successfully built TSS.UWP.
                          3. Created new universal project for windows 10 in VS2015
                          4. Added TSS.UWP in solution and took its reference in universal project
                          5. Copied Program.cs of Authorization sample project of TSS.NET and edited it according to UWP requirements.
                          6. Unsuccessful build.

Below are attached screenshots for reference. Please let me know if you get the solution.

![uwp_exception](https://cloud.githubusercontent.com/assets/19467081/15391168/50ddb048-1ddd-11e6-8b59-e2024edf31dc.png)

Thanks in advance.

**Comment by RonaldAi** [comment]
Hi,
Thank you for your feedback. If you look in Tpm2Devices.cs, the TcpTpmDevice is only included if the preprocessor define TSS_NO_TCP is set. Can you check if your project's "build" configuration includes this define? If so, removing it should allow you to use TcpTpmDevice.
Thank you, Ronald.

**Comment by RutujaWanjari** [comment]
Thankyou for quick response.

Universal project(HPTest_2) build configuration includes,
Condition Compilation Symbols as- NETFX_CORE;WINDOWS_UWP;CODE_ANALYSIS
So I didn't edit it.

While the TSS.UWP build configuration includes,
Condition Compilation Symbols as - 
NETFX_CORE;WINDOWS_UWP;TSS_NO_TCP;TSS_USE_BCRYPT;TSS_NO_STACK;TSS_MIN_API
From this, if I remove TSS_NO_TCP  I get errors related to Network classes like attached in the snap.

Are you suggesting to modify code of TcpTpmDevice according to Network APIs supported by UWP?? Because as you see many .NET APIs are not supported in UWProject.

![tss_uwp_builderrors](https://cloud.githubusercontent.com/assets/19467081/15399594/f3390a2c-1e05-11e6-9037-9a309fe928a0.png)
![universalproject_buildconfig](https://cloud.githubusercontent.com/assets/19467081/15399593/f337eb6a-1e05-11e6-9d71-1238600b04c7.png)

**Comment by RonaldAi** [comment]
Thank you for the feedback. We'll see if we can address the network issue in TSS.UWP in a future release. If you don't want to release your program for Windows phone or XBox, you might be able to use TSS.Net instead.
Hope that helps, Ronald.

**Comment by ArquintL** [comment]
@RonaldAi 
I'm trying to use TSS.MSR in a background application for the Windows IoT core (for the ARM architecture). 
I added the NuGet package to the C++ project. However, TSS.MSR does not show up in the References section.
In the style of this issue, I've created a new Universal Visual C# Windows Runtime Component project and added all C# source files. Unfortunately, compilation fails because `ECDiffieHellmanCng` as well as `RNGCryptoServiceProvider` can not be found.

Do you have an idea what goes wrong with my setup?
