### ISSUE TITLE
PCP tool fails with ERROR - PcpToolDecodeLog(): (0x80070057) The parameter is incorrect.

### ISSUE THREAD

**Issue by raldone01** [microsoft/TSS.MSR#122]
I tried to find out what pcrs change to find out why bitlocker recovery is triggered.
The tool fails after the first wbcl entry with the following output:
```
PS C:\Users\_\Downloads\PCPToolKit\PCPTool\Debug> .\PCPTool.exe decodelog C:\Windows\Logs\MeasuredBoot\0000000001-0000000000.log
<TCGLog>
  <WBCL size="79783">
    <EV_No_Action PCR="00" Digest="0000000000000000000000000000000000000000" Size="33">
      53706563204944204576656e743033000000000000026902010000000b00200000
      <!-- Spec.ID.Event03.......i.......... -->
    </EV_No_Action>
ERROR - PcpToolDecodeLog(): (0x80070057) The parameter is incorrect.
```
I traced the issue to the following line:
Support.cpp:
```cpp
// Ensure that the have a valid entry
        if(((PBYTE)pEntry - pbWBCL + cbEntry) > cbWBCL)
        {
            hr = E_INVALIDARG;
            goto Cleanup;
        }
```
The error is triggered after the first iteration. 
On the first iteration cbsize is: 65
On the second iteration cbsize is: 1799293219
Which obviously is incorrect.
I suspect this is due to an offset error in the wbcl log.

Is there an easier tool to view the changed pcrs?

**Comment by RonaldAi** [comment]
Yeah, PCPTool is not maintained.
Try downloading TBSLogGenerator.exe (https://docs.microsoft.com/windows/security/information-protection/bitlocker/ts-bitlocker-decode-measured-boot-logs) and use that with '-lf <measured boot log>' parameter.
