### ISSUE TITLE
Getting TbsCommandBlocked Exception when I try to run NV (UWP) sample

### ISSUE THREAD

**Issue by rahulkps23** [microsoft/TSS.MSR#127]
Getting exception as:

> Exception occurred: Error {TbsCommandBlocked} was returned for command NvDefineSpace.
Details:
[Code=TpmRc.TbsCommandBlocked],[RawCode=0x80280400,2150106112]
[ErrorEntity=Unknown], [ParmNum=0]
[ParmName=Unknown]

When I try to run NV (UWP) sample.

[Similar Issue](https://stackoverflow.com/questions/70616619/getting-tbscommandblocked-exception-when-i-run-the-microsoft-tss-msr-authorizati)

**Comment by RonaldAi** [comment]
did you run the sample as Admin or Standard User? If the latter, this is expected. Try to run the NV sample as Admin,
