### ISSUE TITLE
TSS.CPP samples are failing

### ISSUE THREAD

**Issue by monsieur7** [microsoft/TSS.MSR#128]
C:\Users\nolan\Downloads\TSS.MSR\TSS.CPP\bin\x64\Debug>"TSS.CPP Samples.exe"
Connect failed
TpmCppTester: Could not connect to TPM device.
Exiting...

I have a tpm (I'm on windows 11). What can I do ?

**Comment by RonaldAi** [comment]
Without argument, the samples executable tries to connect to a simulator. If you want to interface with your TPM device, please specify the argument 'tbs'. For instance: "TSS.CPP Samples.exe" tbs
