### ISSUE TITLE
.NET app that accesses TPM throws error on a shared library 'libtss2-tcti-tabrmd.so' on RHEL VM

### ISSUE THREAD

**Issue by dsaiju** [microsoft/TSS.MSR#161]
I am writing a .NET core application that stores and reads strings to TPM storage and it is targeted for both Windows and Red Hat Linux VMs. I'm using Microsoft.TSS (2.1.1) NuGet package for this purpose. I can store and retrieve data on Windows machine but the same code throws following exception on RHEL VM while storing the strings:

`Exception while loading tpm2-abrmd: System.DllNotFoundException: Unable to load shared library 'libtss2-tcti-tabrmd.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibtss2-tcti-tabrmd.so: cannot open shared object file: No such file or directory at Tpm2Lib.AbrmdWrapper.NativeMethods.Tss2_Tcti_Info() at Tpm2Lib.AbrmdWrapper.Load(IntPtr& tctiCtxPtr) at Tpm2Lib.LinuxTpmDevice..ctor(String tpmDevicePath)`

Note: I have installed the following packages already: tpm2-abrmd, tpm2-pkcs11, tpm2-tools. Any suggestions will be helpful.

**Comment by amarochk** [comment]
IIRC, in the past it used to come from a separate package `libtss2-tcti-tabrmd0`.

**Comment by dsaiju** [comment]
thanks for the reply @amarochk. got it. I can store and read data fine even after this exception. so I guess, this error can be ignored.
