### ISSUE TITLE
Win10 AnnUpdate

### ISSUE THREAD

**Issue by MarioGomezR4** [Microsoft/TSS.MSR#2]
Hi folks. I'm no expert on TPM because I never had an issue as important as the next Win10 update.
I probably shouldn't post this here, but since you're related to the subject... here's my question:

If my hardware doesn't support (nor has) a hardware-based TPM module: may I simulate it with one of your tools?

Otherwise, Win10 Anniversary Update won't install on my PC :(

Thanks in advance.

Mario.

**Comment by RonaldAi** [comment]
Hi Mario,
Thank you for your interest in TSS.MSR. 
The Win10 Anniversary Update will install just fine on any machine that is already running Windows 10 (or 7 or 8).
The requirement to have a TPM 2.0 is for new hardware that OEMs want to get Windows Logo certified for Win10 Anniversary Update. I.e., if an OEM wants to sell a new machine after July 28th 2016 and put a sticker on it that states "Certified for Windows 10 Anniversary Update", that machine will need a TPM 2.0.
Hope that helps, Ronald.

**Comment by MarioGomezR4** [comment]
Thank you Ronald. What about the Win10 AU images we'll (users) download from Microsoft servers (using MediaCreationTool.exe) after July 28th?

If we try to fresh-install those on our non-TPM PCs, will we succeed? I mean, won't the installation abort complaining about the non existent hardware-based TPM?

Sorry to be insistent on the subject, but I really wanna be sure...
I appreciate the time you take in order to answer me.

**Comment by RonaldAi** [comment]
Hi Mario,
(with the caveat that I don't know what hardware you want to install on...)
A fresh install of the Win10 Anniversary Update should install on all hardware that Windows 10 could be installed on. One only knows for sure once they try :) .
Again, the requirement for TPM 2.0 is for OEMs that build new hardware after July 28th 2016, not for existing hardware.
Hope that helps, Ron.
