### ISSUE TITLE
Running TSS Samples in Windows with real hardware TPM ( TPM_E_COMMAND_BLOCKED)

### ISSUE THREAD

**Issue by rsUserOne** [Microsoft/TSS.MSR#20]
Running the TSS samples on Windows with the real hardware TPM is a challenge because, by default, Windows is restricting the TPM commands through Local Policy. Once you figure it out how to disable the local policy , the TPM commands are sent down to the TPM. BUT not ALL !!  The Samples::ChildKeys() example is still failing with the error code  TPM_E_COMMAND_BLOCKED. Has anyone managed to run this sample on real TPM ( not on the simulator) ?

**Comment by amarochk** [comment]
Commands creating TPM objects normally require administrator privileges.
