### ISSUE TITLE
TcpTpmDevice missing

### ISSUE THREAD

**Issue by smoms** [Microsoft/TSS.MSR#21]
In the example provided in the Azure doc i see the demo using the TcpTpmDevice class (TCP/socket communication to the TPM). Why is not present in this project? Here there are only the InprocTpm and TbsDevice implementation?

thanks,
Antonio

**Comment by amarochk** [comment]
It's here: https://github.com/Microsoft/TSS.MSR/blob/9fb1fac9ee6b7ee2dfe8040069ae68e09d948d0d/TSS.NET/TSS.Net/TpmDevices.cs#L306
