### ISSUE TITLE
Fail to compile TSS.CPP on linux

### ISSUE THREAD

**Issue by oferch** [Microsoft/TSS.MSR#26]
Hi,
I'm trying to compile the TSS.CPP on Ubuntu 18.04 LTS with gcc-7
I get many "Incomplete type" errors:
e.g.
gcc -Wall -c -g -fPIC -D _TPMCPPLIB -std=c++11 -I../Src AuthSessions.cpp
In file included from /usr/include/c++/7/vector:64:0,
                 from fdefs.h:63,
                 from Helpers.h:13,
                 from TpmStructureBase.h:8,
                 from TpmTypes.h:8,
                 from Tpm2.h:8,
                 from stdafx.h:59,
                 from AuthSessions.cpp:10:
/usr/include/c++/7/bits/stl_vector.h: In instantiation of ‘struct std::vector<TpmCpp::TPMS_PCR_SELECTION>::_Temporary_value’:
fdefs.h:117:46:   required from here
/usr/include/c++/7/bits/stl_vector.h:1467:33: error: invalid application of ‘sizeof’ to incomplete type ‘TpmCpp::TPMS_PCR_SELECTION’
  typename aligned_storage<sizeof(_Tp), alignof(_Tp)>::type __buf;
                                 ^
/usr/include/c++/7/bits/stl_vector.h: In instantiation of ‘struct std::vector<TpmCpp::TPMS_TAGGED_PCR_SELECT>::_Temporary_value’:
fdefs.h:118:46:   required from here
/usr/include/c++/7/bits/stl_vector.h:1467:33: error: invalid application of ‘sizeof’ to incomplete type ‘TpmCpp::TPMS_TAGGED_PCR_SELECT’
/usr/include/c++/7/bits/stl_vector.h: In instantiation of ‘struct std::vector<TpmCpp::TPMS_TAGGED_PROPERTY>::_Temporary_value’:
fdefs.h:119:46:   required from here

Any Idea?

**Comment by jtakeshi** [comment]
This issue also appears on my machine (Ubuntu 18.04, gcc 7.3.0). Compilation still fails when using C++14 instead of C++11.

**Comment by mohandatla** [comment]
I am hitting same error with Ubuntun 18.10 with C++11

**Comment by amarochk** [comment]
Must be fixed now.

**Comment by mohandatla** [comment]
> Must be fixed now.

I verified on Ubuntu 18.10, it looks good. Thank you so much Andrey for fixing it.
