### ISSUE TITLE
TcpTpmDevice is ignoring SetSocketTimeout

### ISSUE THREAD

**Issue by CIPop** [Microsoft/TSS.MSR#29]
There are two issues:

1. `TcpTpmDevice` doesn't use the SocketTimeout. (Offline discussion with @amarochk.) 
2. `TcpTpmDevice.SetSocketTimeout` fails before calling `Connect()`. 

For some simulators (real TCP TPM resourcemanagers?) connecting from two different clients at the same time causes one of them to block during `Connect()` on `Socket.Receive()`. We should have a way to avoid the situation by timing out for both the TCP connect and r/w operations.

**Comment by amarochk** [comment]
Fixed
