### ISSUE TITLE
Built Against a downlevel version of OpenSSL

### ISSUE THREAD

**Issue by RussellGantman** [Microsoft/TSS.MSR#30]
Are there plans to link against the latest version of OpenSSL (1.1.1.a)? The version you are using is 1.0.2o.

**Comment by amarochk** [comment]
We do not have immediate plans of upgrading the OpenSSL dependency. But if you would like to go ahead, and submit the PR with the upgrade, we'll gladly accept your contribution.

**Comment by mariobr** [comment]
Hi Russel, I have it compiling/linking against  openssl/1.1.1i.
I am using CMAKE and Conan for the package retrieval.
