### ISSUE TITLE
Request to switch to a Logging framework

### ISSUE THREAD

**Issue by paul4334** [Microsoft/TSS.MSR#31]
I am using TSS.CPP for a work project and would like to limit the messages printed to STDOUT and STDERR. It is working quite well for me, but I wondering if this project can be switch to using a logging framework to allow informative/warning/error messages to be disabled or redirected to another log destination when compiling for release.
Thank you

**Comment by amarochk** [comment]
I've removed a few stray printfs, and there are only a few more remaining, all in the simulator device abstraction, which is not what is used in any production code. Otherwise the library relies on error codes or exceptions. There is no need or plans to involve any logging framework.
