### ISSUE TITLE
Windows Store Certification Failure

### ISSUE THREAD

**Issue by danebou** [microsoft/TSS.MSR#34]
(Original post on [azure-iot-sdk github](https://github.com/Azure/azure-iot-sdk-csharp/issues/858))

As if a few weeks ago, the windows store app review updated their requirements which caused our app to fail the review.

Starting from a bare-bones passing UWP app, adding the `Microsoft.TSS` package causes the review to fail:

> FAILED
>     Supported APIs
> 
>     Error Found: The supported APIs test detected the following errors:
>         API SetDllDirectoryW in kernel32.dll is not supported for this application type. TestUpload.dll calls this API.
>     Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
>     How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these environments may pull in unsupported APIs. Retest your app in a release configuration, and with .NET Native enabled if applicable. See the link below for more information:
>     Alternatives to Windows APIs in Microsoft Store apps. 

**This means no app that contains this package can get published on the windows store.**

The source of this is likely the import of `SetDllDirectory()` in `TbsDevice.cs`

**Comment by amarochk** [comment]
I've removed the class that caused this warning from the UWP build. You can try and build the UWP version of TSS.Net and see if your app works.

**Comment by danebou** [comment]
@amarochk I had to make a modification and it passes now.

**Comment by danebou** [comment]
@amarochk I'm a bit confused now after the last commit. Is the UWP project or the regular project used for nuget packages? If its the main project, then the `SetDllDirectory` is still there and this issue is unresolved.

**Comment by amarochk** [comment]
My original fix was incorrect as it left the problem classes in UWP builds, and removed them in builds for other framework version. My last fix removed the unsupported API from UWP build (that uses TSS.Net.UWP.csproj), but returned them into other versions. The nuget contains the binaries produced by all projects for various frameworks. Actually you should not be able to build a UWP version with the regular project, at least it did not work for us.

**Comment by amarochk** [comment]
Actually, the title of the issue must be incorrect - I guess that was what misguided me in my initial commit. You only need the SetDllDirectory() calls removed in UWP version of the library, right?

**Comment by danebou** [comment]
I guess we need it removed from the [Nuget Package](https://www.nuget.org/packages/Microsoft.TSS/

**Comment by danebou** [comment]
On a side note, I had to enable `TSS_USE_BCRYPT` but I was able to get it the UWP to build after that.

**Comment by amarochk** [comment]
Wait a sec, what do you mean "had to enable TSS_USE_BCRYPT"? TSS_USE_BCRYPT should be enabled by default for both project types, at least with "Any CPU" platform target.

**Comment by amarochk** [comment]
And, I cannot remove SetDllDirectory() usage from non-UWP versions of the library. Though I believe it should not be a problem for you, as you use UWP.

**Comment by danebou** [comment]
I see, I'm targeting `ARM` (`TSS_USE_BCRYPT` defaults to disabled for `ARM`).

This fixes it
```
diff --git a/TSS.NET/TSS.Net.UWP/TSS.Net.UWP.csproj b/TSS.NET/TSS.Net.UWP/TSS.Net.UWP.csproj
index b690fdd..5c505dc 100644
--- a/TSS.NET/TSS.Net.UWP/TSS.Net.UWP.csproj
+++ b/TSS.NET/TSS.Net.UWP/TSS.Net.UWP.csproj
@@ -62,7 +62,7 @@
     <PlatformTarget>ARM</PlatformTarget>
     <DebugSymbols>true</DebugSymbols>
     <OutputPath>bin\ARM\Debug\</OutputPath>
-    <DefineConstants>TRACE;DEBUG;WINDOWS_UWP;__MonoCS__;TSS_NO_STACK</DefineConstants>
+    <DefineConstants>TRACE;DEBUG;WINDOWS_UWP;__MonoCS__;TSS_NO_STACK;TSS_USE_BCRYPT</DefineConstants>
     <NoWarn>;2008</NoWarn>
     <DebugType>full</DebugType>
     <PlatformTarget>ARM</PlatformTarget>
@@ -72,7 +72,7 @@
   <PropertyGroup Condition="'$(Configuration)|$(Platform)' == 'Release|ARM'">
     <PlatformTarget>ARM</PlatformTarget>
     <OutputPath>bin\ARM\Release\</OutputPath>
-    <DefineConstants>TRACE;WINDOWS_UWP;__MonoCS__;TSS_NO_STACK</DefineConstants>
+    <DefineConstants>TRACE;WINDOWS_UWP;__MonoCS__;TSS_NO_STACK;TSS_USE_BCRYPT</:
```

**Comment by danebou** [comment]
I'm not sure who needs the DLL support or its use case, but is it possible to add another if-def `DYNAMIC_DLL_LOAD`, so the nuget package defaults to disabling that feature? Then those who still require that support can still enable that for the local project. 

The other option would be to get in touch with the windows store review and try to add an exception for this package (if that's possible).

It just seems a bit weird how this package which IoT devices depend on can't be used in Windows Store apps.

**Comment by amarochk** [comment]
I do not understand why are you concerned about the in-proc variant everywhere? It should only matter in UWP DLL, as it is the one used in WinStore apps.

As for the ARM target platform, the nuget only contains UWP package built for the "Any CPU" target. Yet I can add TSS_USE_BCRYPT to the ARM configuration, if it will make your life easier.

**Comment by danebou** [comment]
> And, I cannot remove SetDllDirectory() usage from non-UWP versions of the library. Though I believe it should not be a problem for you, as you use UWP.

`<file src="lib\uap10.0\TSS.Net.dll" target="lib\uap10.0\TSS.Net.dll" />`
Ah, I see now. The UAP version is a separate DLL, but still included in the nuget package. Then removing it for just the UWP variant should work.

**Comment by danebou** [comment]
@amarochk any updates?

**Comment by amarochk** [comment]
I've committed my changes earlier this week, and now we are waiting for the binaries and the new nuget package to be signed.

**Comment by danebou** [comment]
Sorry to bother you again, but any more updates?

> I've committed my changes earlier this week, and now we are waiting for the binaries and the new nuget package to be signed.

**Comment by danebou** [comment]
We haven't made any changes since then, but it appears the windows store review reverted their requirements since we can publish now. I guess this fix has been merged anyway. Thanks for the all the help again!
