### ISSUE TITLE
How to export public key?

### ISSUE THREAD

**Issue by rquackenbush** [microsoft/TSS.MSR#36]
In looking at the sample code for `Signing`, it looks like there may have once been code to export the public key. Was this code removed (as hinted to in the NOTE).

How do I get the public key into a usable format (xml, pem, x509, etc)?

```c#
// NOTE: 12-JAN-2016: May be removing support for policy
//       serialization. We'd like to get feedback on whether
//       this is a desirable feature and should be retained.
//
// {
//     const string fileName = "sample.xml";
//     string xmlVersionOfObject = keyPublic.GetXml();
//     keyPublic.XmlSerializeToFile(fileName);
//     var copyOfPublic = TpmStructureBase.XmlDeserializeFromFile<TpmPublic>(fileName);
```

**Comment by amarochk** [comment]
You can use whatever serialization method available for .Net data structures/classes suits you the best. In particular standard Data Contract serializers are supported (such as DataContractSerializer and DataContractJsonSerializer).
