### ISSUE TITLE
Can not Deserialize Quote

### ISSUE THREAD

**Issue by batyrchary** [microsoft/TSS.MSR#37]
Hello,

I am trying to Serialize Quote and send it to remote party and Deserialize it on remote party.

So currently I am just trying to Serialize and Deserialize Quote on my local machine.

This is currently what I have

QuoteResponse quote = GenerateQuote_PCR(tpm, rmessage.startPCR, rmessage.endPCR, NonceExtracted);

cout << "serialization:" << endl;
string qserialized=quote.Serialize(SerializationType::Text);
cout << "serialization done" << endl;

QuoteResponse quoteDeserialized=QuoteResponse();

cout << "deserialization:" << endl;
quoteDeserialized.Deserialize(SerializationType::Text, qserialized);
cout << "deserialization done" << endl;

I checked if  quote generated by GenerateQuote_PCR function is generated correctly.

this is the line that gives me error
quoteDeserialized.Deserialize(SerializationType::Text, qserialized);

Any help will be appreciated.

Thanks
Batyr

**Comment by amarochk** [comment]
All TPM data structures in TSS.Net support DataContractSerializer interface. For example:

```C#
            Attest quote = tpm.Quote(hSigKey, hashToSign, new SchemeRsassa(sigHashAlg),
                                     outSelection, out quoteSig);
            var ms = new MemoryStream();
            var dcs0 = new DataContractSerializer(typeof(Attest));
            dcs0.WriteObject(ms, quote);
            ms.Flush();
            byte[] serializedRepr = ms.ToArray();
            var dcs1 = new DataContractSerializer(typeof(Attest));
            var restoredQuote = (Attest)dcs1.ReadObject(new MemoryStream(serializedRepr));
```

Alternatively, all TPM data structures in TSS.Net have a pair of `ToNet()/ToHost()` methods that marshal/unmarshal a TPM object to/from a portable binary representation (see the `TpmStructureBase.GetTpmRepresentation()` helper for an example of `ToNet()` usage).
