### ISSUE TITLE
PolicyNvWritten implementation

### ISSUE THREAD

**Issue by ShanyYang** [microsoft/TSS.MSR#38]
Hi guys, I can't find the PolicyNvWritten implementation in Policy.h and cpp file.
I wrote and tested on my project.
here, I show you my code.

[Policy.h.cpp.txt](https://github.com/microsoft/TSS.MSR/files/3288799/Policy.h.cpp.txt)

**Comment by amarochk** [comment]
Hi Shany,

Your changes look good. Feel free to submit a PR (and it would be great if you added you test code to the samples, too).

Thanks,
-Andrey
