### ISSUE TITLE
TPM ContextSave returns 0x80280400 (TPM_E_COMMAND_BLOCKED)

### ISSUE THREAD

**Issue by gaetanww** [microsoft/TSS.MSR#39]
Hi,

I've been using the TSS.NET project against a hardware TPM. I create a primary key using CreatePrimary command and then ContextSave. I'm running the script from an adminitrator command line and keep getting the 0x80280400 (TPM_E_COMMAND_BLOCKED) error. 

I've tried removing the block command using the Win32_TPM WMI object and setting the registry keys to ignore the default and local list.

When I run the Win32_TPM `IsCommandBlocked(184)` it tells me that the command isn't blocked anymore, but the TBS keeps failing with the same error. Is there something I'm doing wrong?
Thank you for your help.

**Comment by amarochk** [comment]
TPM2_ContextSave() is reserved for OS purposes (to implement TPM Resource Manager logic), and it should not be required  for any user app purposes (note that it, in particular, does not preserve the object across reboots).

You can always call TPM2_CreatePrimary() again with the same key template to get exactly the same key. If you want to avoid the cost of the key generation, you can use TPM2_EvictControl() to persist the key in TPM's NV memory. Alternatively you can use TPM2_Create() to create a non-primary key, store the returned private and public blobs on disk, and then load them into the TPM at any moment the key is needed.

**Comment by gaetanww** [comment]
Thank you for the information. I imagine that the Win32_TPM `RemoveBlockedCommand(184)` sould return an error in that case. And `IsCommandBlocked(184)` should return `false`.
Do you know where I can report that bug?
