### ISSUE TITLE
TSS.NET GetTime

### ISSUE THREAD

**Issue by Haritha1612** [microsoft/TSS.MSR#40]
Hi,

I'm currently implementing TPM2 GetTime Command using TSS.NET and have noticed that the response (Attest) includes ClockInfo. I would like the method to return TimeInfo as well. Is there a method available that does GetTime() and also return Time Info?

Any help will be much appreciated.

Thanks & Regards,
Haritha

**Comment by amarochk** [comment]
Hi Haritha,

You need to remember that the methods exposed by TSS are just wrappers for TPM 2.0 commands. So, their semantics is predefined by the TPM 2.0 specification. If you need to retrieve TimeInfo data structure, you can use the ReadClock() command.

-Andrey
