### ISSUE TITLE
TpmHandle.CreatePrimary throws BadAuth exception

### ISSUE THREAD

**Issue by davidmn** [microsoft/TSS.MSR#43]
Following the .NET example in Samples/Signing I am having an issue when using a physical TPM.

I look up the value of OwnerAuthFull in the registry at `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TPM\WMI\Admin` and let's say the value is "foo/bar=". This is also displayed when I run Get-Tpm on the command line.

So I create the AuthValue by turning the string to bytes and create the AuthValue

```
var authValueRegistry = Encoding.ASCII.GetBytes( "foo/bar=" );
var ownerAuth = new AuthValue( authValueRegistry );
```

Then I get to creating a primary key with the example:

```
var keyHandle = tpm[ownerAuth].CreatePrimary(
					TpmRh.Owner,                            // In the owner-hierarchy
					new SensitiveCreate( keyAuth, null ),     // With this auth-value
					keyTemplate,                            // Describes key
					null,                                   // Extra data for creation ticket
					new PcrSelection[ 0 ],                    // Non-PCR-bound
					out keyPublic,                          // PubKey and attributes
					out creationData, out creationHash, out creationTicket );    // Not used here
				Console.WriteLine( "New public key\n" + keyPublic.ToString() );
```

Running this throws an exception with the message `Error {BadAuth} was returned for command CreatePrimary`

I'm not sure where to go with this to debug further, if it's usage error then I'll happily add some extra explantation to the example.

**Comment by amarochk** [comment]
This is actually not a TSS issue. The value in the registry is evidently not an OwnerAuth value. Windows 10 by default uses an empty auth value for the owner hierarchy. If it is configured to use a non-empty OwnerAuth value, it is not stored in the registry anymore (and I do not think there is a public API to retrieve it).

Also, note that OwnerAuthFull in Windows parlance is a LockoutAuth value. And it cannot be retrieved from the registry or via any public API either...
