### ISSUE TITLE
Provide ECDH get secret example

### ISSUE THREAD

**Issue by RussellGantman** [microsoft/TSS.MSR#44]
Is it possible to give an example on generating an ECDH secret from a key created using TSS and an imported public key?

I do not see any examples on DH key exchanges in the samples.

**Comment by amarochk** [comment]
Do you mean "using a TPM key created via the TSS interface, and an ephemeral public key loaded into the TPM"?

**Comment by RussellGantman** [comment]
Not really. I created aand stored a key in the NV area of the TPM (as a platform key for my device). I need to use the private portion of that key to create the secret with a public portion from my "Alice"

**Comment by amarochk** [comment]
Well, it is essentially what I described. You have a key created in the TPM, then you use LoadExternal() to load the public part of your "Alice" key, and then you'll need to use EcdhZGen() to generate the shared secret. Most cryptographic protocols expect your "Alice" key to be an ephemeral (i.e. single use) one, and the result of EcdhZGen() is usually used as a seed for a derivation scheme.

On the client side, you use the public part of your TPM key, and private part of your ephemeral key to generate the shared secret. TPM has a command that encapsulates both ephemeral key and shared secret generation: EcdhKeyGen().
