### ISSUE TITLE
Cannot run this lib on a raspberry pi

### ISSUE THREAD

**Issue by Gebov** [microsoft/TSS.MSR#45]
Hi,

I am attempting to use this lib (it came alongside the package Microsoft.Azure.Devices.Provisioning.Security.Tpm) on a Raspberry PI, but I get the following error.

![image](https://user-images.githubusercontent.com/4221529/67623667-aad95800-f830-11e9-9663-fa17b98de422.png)

**Comment by amarochk** [comment]
It looks like your device does not have a TPM device enabled (neither /dev/tpm0 or /dev/tpmrm0). TSS tried to connect to a locally running TPM simulator then, and, since it was not available either, threw an exception.
