### ISSUE TITLE
How to use OpenSSL 

### ISSUE THREAD

**Issue by naaeef** [microsoft/TSS.MSR#47]
Hello,
I'd like to use the TSS.MSR project as an engine for OpenSSL.
Is there any documentation, which shows how to use the TSS.MSR as an OpenSSL engine or could you provide a sample?

Thank you for your help.

**Comment by amarochk** [comment]
No, TSS.MSR has never been considered as an engine for the OpenSSL library.

**Comment by naaeef** [comment]
@amarochk thank you for your quick response. Could you explain what your last commit message "Added support for 64-bit build and OpenSSL 1.1" in the folder TSS.CPP means? In what way is OpenSSL 1.1 supported?

**Comment by amarochk** [comment]
The TPM 2.0 reference implementation does not implement all the cryptographic algorithms it needs. 
Instead it defines an abstraction layer that allows it to use existing crypto libraries  such as OpenSSL. So the relation here is exactly inverse to what you inferred.

Yet, the idea of using a hardware TPM as an engine for OpenSSL has merits of its own. It is just that this is more of a task for the community of OpenSSL users...
