### ISSUE TITLE
Support for TPMv1.2

### ISSUE THREAD

**Issue by yelizyilmaz** [microsoft/TSS.MSR#48]
Here's the issue.

In Microsoft's Dev Center, it is described that both v1.2 and 2.0 can be supported at the same time by using TBS_CONTEXT_PARAMS2 structure (which was described in C++).

**However**
TSS.MSR Java Library won't support versions other than 2.0. Although Microsoft's lower-layer library have a field for that (_includeTpm12_), we cannot specify it under version field in the class TBS_CONTEXT_PARAMS2 which is in TpmDeviceTbs.java file.

"version" and "params" are hardcoded as;

_parms.version = 2;
parms.params = 1 << 2;_

in TpmDeviceTbs.java. I guess that we cannot specify any other value to include TPM1.2. Am I correct in this that this library will not support TPM v1.2 ?

**Comment by yelizyilmaz** [comment]
Hello? Anybody out there?

**Comment by DavidWooten** [comment]
No 1.2.

**Comment by yelizyilmaz** [comment]
Okay, you could've just written "There is no v1.2 support and there won't be". What does "NO 1.2" mean?

**Comment by DavidWooten** [comment]
What do you think it means?

**Comment by yelizyilmaz** [comment]
Okay.
