### ISSUE TITLE
fdefs.h has "using namespace std;" in it, causes issues

### ISSUE THREAD

**Issue by kandersondaxsonics** [microsoft/TSS.MSR#50]
The following is on line 54/55 in TSS.CPP/Src/fdefs.h
```
using namespace std;
typedef unsigned char byte;
```
This causes issues throughout the library using this in C++17 as [std::byte](https://en.cppreference.com/w/cpp/types/byte) is now a thing.  It can't resolve the typedef of byte here versus std::byte in the other files.  This is on VS 2019 Professional v16.4.2.

Recommend removing `using namespace std` and changing the declarations that depend on this to avoid `using` this way in .h files.

**Comment by RonaldAi** [comment]
Thanks for reporting this issue. Could you prepare a pull request with the fix? Thanks!

**Comment by kandersondaxsonics** [comment]
In my opinion you should not have kept the `using namespace std;` directive. for this fix.  I'm sorry for not replying and saying I didn't have time to fix it, but the solution is _not_ to double-down on the bad practice and keeping that directive.  You're violating _all_ best practices I've ever heard of for C++, _including Microsoft's._  The big "note" block at the link below shows it:

[C++ Language Reference - Namspaces](https://docs.microsoft.com/en-us/cpp/cpp/namespaces-cpp?view=vs-2019#using_directives)

> A using directive can be placed at the top of a .cpp file (at file scope), or inside a class or function definition.
> 
> In general, avoid putting using directives in header files (*.h) because any file that includes that header will bring everything in the namespace into scope, which can cause name hiding and name collision problems that are very difficult to debug. Always use fully qualified names in a header file. If those names get too long, you can use a namespace alias to shorten them. (See below.)

The `using namespace std;` should have been removed (that's the largest sin here), and the byte typedef (though it should have been a `using byte = unsigned char;` for C++11 or higher) put inside the namespace for TpmCpp.  And then fix all the .h files where you neglected to put `std::` in front of the classes/functions/objects that needed them.  You can put `using namespace std;` in the C++ files if you'd like (below the `#include`s of course), but keep it out of the .h files!
