### ISSUE TITLE
Library crashes with 0xC0000008 on TpmTbsDevice::Connect function failure

### ISSUE THREAD

**Issue by ezhukov-softeq** [microsoft/TSS.MSR#51]
When function Tbsi_Context_Create fails to create context  output variable context is not initialized in constructor. 
In addition at cleanup phase Tbsip_Context_Close function is called as 
```
Tbsip_Context_Close(&context)
```
 but should be 
```
Tbsip_Context_Close(context)
```

**Comment by RonaldAi** [comment]
Thanks for your feedback. Could you prepare a pull request with your fix? Thanks!

**Comment by amarochk** [comment]
Fixed as suggested: https://github.com/microsoft/TSS.MSR/commit/5b32b4d2ce70eaa95f7ec1219fc6a9b187acd7e6.
