### ISSUE TITLE
Policy_AC_SendSelect FAILED! RC: 0x80280400--TPM_E_COMMAND_BLOCKED

### ISSUE THREAD

**Issue by shensongwu** [microsoft/TSS.MSR#57]
Hello there,

I'm using this TSS and Policy_AC_SendSelect(TPM2 command 0x194) gets blocked by TBS.

And I follow https://docs.microsoft.com/en-us/windows/win32/tbs/command-blocking 
to try to unblock this command. I read carefully to this link but it still can't work. Looks like the document is out of date.

Any thought that could help me out?

Thanks

**Comment by amarochk** [comment]
Yes, TPM management interfaces available for the user in Windows have changed a lot. I've redirected the question to the Windows people, and will let you know if I get any definitive answer.

**Comment by RonaldAi** [comment]
Hi Shensongwu, the documentation on command blocking needs to be updated to indicate that for TPM 2.0 the allowed/blocked commands are hard-coded in the TPM driver. We do have a fix for the next Windows release that we plan to backport. Which Windows release do you need this command supported on? Thanks.
