### ISSUE TITLE
Thread-saftey of TSS.NET

### ISSUE THREAD

**Issue by rhegner** [microsoft/TSS.MSR#59]
I'm new to TSS.NET (and TPM in general), and I'm wondering about the thread-safety guarantees provided by TSS.NET.

1. Is it safe to execute (async or synch) operations on a single `Tpm2` object from multiple threads?
2. If not, is it safe to execute (async or synch) operations on a single `Tpm2Device` object from multiple threads (using a separate `Tpm2` instance on every thread)?
3. If not, is it safe to execute (async or synch) operations from multiple threads using a separate `Tpm2Device` instance per thread?

And as a bonus question: What's the current state of TSS.NET? Is it considered safe to use it in production? Does it work well under both Linux and Windows? Any limitations I should be aware of before I dig into TSS.NET deeper?

**Comment by amarochk** [comment]
NO to 1 and 2, YES to 3.

TSS.Net has been used by Windows, Azure, and internally by most of major TPM manufacturers for years. You can use either the latest available [nuget](https://www.nuget.org/packages/Microsoft.TSS/), or just take the latest master snapshot - it is (normally) maintained in stable state.

**Comment by amarochk** [comment]
As an additional option, you can actually use 1, as long as you implement the synchronization necessary to serialize operations on the Tpm2 object in different threads.
