### ISSUE TITLE
'tag': is not a member of 'TpmCpp::TPMT_TK_HASHCHECK'

### ISSUE THREAD

**Issue by dkov01** [microsoft/TSS.MSR#60]
Hallo,
TSS.CPP doesn't compile due to the following errors:
`error C2661: 'TpmCpp::_TPMT_TK_HASHCHECK::_TPMT_TK_HASHCHECK': no overloaded function takes 3 arguments`
`\tss.msr\tss.cpp\include\extensions\tpmt_tk_hashcheck.h(20): error C2039: 'tag': is not a member of 'TpmCpp::TPMT_TK_HASHCHECK'`
`\tss.msr\tss.cpp\include\extensions\tpmt_tk_hashcheck.h(7): note: see declaration of 'TpmCpp::TPMT_TK_HASHCHECK'`

**Comment by amarochk** [comment]
Fixed in https://github.com/microsoft/TSS.MSR/commit/9c436a5c7f6ef9f644ddd17b851c14d129f3f565
