### ISSUE TITLE
Decrypt and Sign with Storage Root Key

### ISSUE THREAD

**Issue by teenccu** [microsoft/TSS.MSR#65]
This method sample Samples::PrimaryKeys() gives me error
_void Samples::PrimaryKeys()
{
    Announce("PrimaryKeys");

    // To create a primary key the TPM must be provided with a template.
    // This is for an RSA1024 signing key.
    TPMT_PUBLIC templ(TPM_ALG_ID::SHA1,
                      TPMA_OBJECT::sign | TPMA_OBJECT::fixedParent | TPMA_OBJECT::fixedTPM
                        | TPMA_OBJECT::sensitiveDataOrigin | TPMA_OBJECT::userWithAuth,
                      null,  // No policy
                      TPMS_RSA_PARMS(null, TPMS_SCHEME_RSASSA(TPM_ALG_ID::SHA256), 1024, 65537),
                      TPM2B_PUBLIC_KEY_RSA());
.................................................
 // Create the key
    auto newPrimary = tpm.CreatePrimary(TPM_RH::OWNER, sensCreate, templ, null, pcrSelect);_

I feel that here we can creating a SRK but the public template is saying that it is for signing, which seems to be not right. I have noticed that SRK must have  TPMA_OBJECT::decrypt.
It looks to me that signing key can only be created as Child key for SRK. Can anybody confirm my understanding ?

**Comment by amarochk** [comment]
The sample is correct. "Primary key" != "Storage Parent key".

What error are you getting?

**Comment by teenccu** [comment]
Thanks for your response.

I am getting error this following error- **"TPM Error - TPM_RC::VALUE".**

However, in the void Samples::HMAC() , where the template is 
_TPMT_PUBLIC templ(TPM_ALG_ID::SHA256, TPMA_OBJECT::sign | TPMA_OBJECT::fixedParent |
                      TPMA_OBJECT::fixedTPM |  TPMA_OBJECT::userWithAuth,
                      null,
                      TPMS_KEYEDHASH_PARMS(TPMS_SCHEME_HMAC(hashAlg)),
                      TPM2B_DIGEST_KEYEDHASH());_

which also is for signing and it is working fine so what I told earlier is not correct.

In fact  I want to create Root Primary Key  which can be used for signing(tpm.sign()) and RSA encryption/decryption(tpm.RSA_Encrypt()/tpm.RSA_decrypt()). I saw the example 
void Samples::RsaEncryptDecrypt() which is fine for RSAEncrypt/Decrypt but I cannot use tpm.sign().
The public template is
_TPMT_PUBLIC primTempl(TPM_ALG_ID::SHA1,
                          TPMA_OBJECT::decrypt | TPMA_OBJECT::userWithAuth | TPMA_OBJECT::sensitiveDataOrigin,
                          null,  // No policy
                          TPMS_RSA_PARMS(null, TPMS_SCHEME_OAEP(TPM_ALG_ID::SHA1), 2048, 65537),
                          TPM2B_PUBLIC_KEY_RSA(seed));_

If I add the TPMA_OBJECT::Sign it fails in the 
 auto storagePrimary = tpm.CreatePrimary(TPM_RH_NULL, null, primTempl, null, null); with error message **"TPM Error - TPM_RC::SCHEME"**



I am new with TPM handling and I am a bit confused with with the selection of the template.

1. Can you please explain what is meant by  "Primary key" != "Storage Parent key" ?
2. Can I create a Root Primary Key( tpm.CreatePrimary()) which can be capable for signing and encryption/decryption also?

Thanks much for your help on this.

**Comment by amarochk** [comment]
1. See section 23.2 of Part 1 of the TPM 2.0 spec (link in readme).
2. You should never do this (it's a bad cryptographic practice).

The scheme must either be a null scheme or correspond to the type/purpose of the key.

**Comment by teenccu** [comment]
Ok , thanks for you reply. I read the 23.2 of Part 1 of the TPM 2.0 .

But still dont you think the issue void Samples::PrimaryKeys() is an issue as it fails to run in my computer with message "TPM Error - TPM_RC::VALUE" ?

Also my last question do you think it is ok  to create x509certificate from the public keys created as in the sample void Samples::RsaEncryptDecrypt() 

_TPMT_PUBLIC primTempl(TPM_ALG_ID::SHA1,
TPMA_OBJECT::decrypt | TPMA_OBJECT::userWithAuth | TPMA_OBJECT::sensitiveDataOrigin,
null, // No policy
TPMS_RSA_PARMS(null, TPMS_SCHEME_OAEP(TPM_ALG_ID::SHA1), 2048, 65537),
TPM2B_PUBLIC_KEY_RSA(seed));_

In that case I will be writing my own CNGPProvider to use the keys  in certificates using the Tss.cpp lib.

**Comment by amarochk** [comment]
It looks like your TPM has a restriction on the key strength of primary keys. I've updated the test to work in this case.

You can create a cert for any key you want. How it fits the requirements of a particular PKI is a completely different story though, and it's completely outside of the TSS libraries scope.

**Comment by teenccu** [comment]
Hello Amarochk ,

Thanks for you previous replies. Again I am getting a error in sample
void Samples::EncryptDecryptSample() with error TPM Exception: TPM Error - TPM_RC::SUCCESS

 As I progress in writing my provider where I want to create keys for using in certificate and use that provider to access the keys when the certificate is used.

**1.** If I create StoragePrimary Key then it will be with TPMA_OBJECT::decrypt  so then I cannot use that key for signing the certificate in case of self signed or even for signing the CSR request.  So how to handle this situation ? (Is there any sample which can help me to understand the situation)

**2.** MY idea is to create different sets of StoragePrimary keys just by changing the parameter in  TPM2B_PUBLIC_KEY_RSA. In that way I do not need to store the keys and I can generate those everytime with the same seed. Is this a good idea ?
_ByteVec seed = { 1,2,3,4 };
 TPMT_PUBLIC primTempl(TPM_ALG_ID::SHA1,          // Key nameAlg
                          TPMA_OBJECT::decrypt | TPMA_OBJECT::restricted | TPMA_OBJECT::userWithAuth
                            | TPMA_OBJECT::fixedParent | TPMA_OBJECT::fixedTPM | TPMA_OBJECT::sensitiveDataOrigin,
                          null,                   // No policy
                          // Key-parms: How child keys should be protected
                          TPMS_RSA_PARMS(Aes128Cfb, TPMS_NULL_ASYM_SCHEME(), 2048, 65537),
                          TPM2B_PUBLIC_KEY_RSA(seed));_
