### ISSUE TITLE
Error in Tss.createDuplicationBlob()

### ISSUE THREAD

**Issue by wenxinleong** [microsoft/TSS.MSR#70]
I am referring to `TSS.MSR/TSS.Java/src/tss/Tss.java: Tss.createDuplicationBlob()`. The variable `nameAlg` is pointing to parent:
```
TPM_ALG_ID nameAlg = targetParent.nameAlg;
```
The inner wrapper should not be using parent algo:
```
byte[] innerIntegrity = Helpers.byteArrayToLenPrependedByteArray(Crypto.hash(nameAlg, toHash));
```
Correction should be:
```
byte[] innerIntegrity = Helpers.byteArrayToLenPrependedByteArray(Crypto.hash(_publicPart.nameAlg, toHash));
```

**Comment by amarochk** [comment]
A good catch, Justin! Thank you!
