### ISSUE TITLE
Support .NET Core running on linux-arm64

### ISSUE THREAD

**Issue by chrfin** [microsoft/TSS.MSR#73]
I tried using the library on our i.MX8MM SoM running Linux 4.19.35 aarch64. In general I can work with the TPM and e.g. request random numbers, but as soon as hashing is used (e.g. \`CreatePrimary\`) it crashes with the following exception:

> Unhandled exception. System.DllNotFoundException: Unable to load shared library 'bcrypt.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD\_DEBUG environment variable: libbcrypt.dll: cannot open shared object file: No such file or directory  
>   at Tpm2Lib.Native.BCryptOpenAlgorithmProvider(UIntPtr& AlgProvider, String AlgId, String Implementation, UInt32 Flags)  
>   at Tpm2Lib.BCryptAlgorithm.Open(String algName, UInt32 flags)  
>   at Tpm2Lib.BCryptAlgorithm..ctor(String algName, UInt32 flags)  
>   at Tpm2Lib.CryptoLib.HashData(TpmAlgId algId, Byte\[\] dataToHash)  
>   at Tpm2Lib.TpmHash.FromData(TpmAlgId hashAlg, Byte\[\] dataToHash)  
>   at Tpm2Lib.TpmPublic.GetName()  
>   at Tpm2Lib.Tpm2.ProcessName(TpmHandle h, Byte\[\] tpmAssignedName, TpmPublic publicPart)  
>   at Tpm2Lib.Tpm2.UpdateHandleData(TpmCc ordinal, TpmStructureBase inParms, TpmHandle\[\] inHandles, TpmStructureBase outParms)  
>   at Tpm2Lib.Tpm2.DispatchMethod(TpmCc ordinal, TpmStructureBase inParms, Type expectedResponseType, TpmStructureBase& outParms, Int32 numInHandlesNotUsed, Int32 numOutHandlesNotUsed)  
>   at Tpm2Lib.Tpm2.CreatePrimary(TpmHandle primaryHandle, SensitiveCreate inSensitive, TpmPublic inPublic, Byte\[\] outsideInfo, PcrSelection\[\] creationPCR, TpmPublic& outPublic, CreationData& creationData, Byte\[\]& creationHash, TkCreation& creationTicket)

I then search the available libraries in the current (=2.1.1) NuGet package and the source code and discovered the following:  
In https://github.com/microsoft/TSS.MSR/blob/master/TSS.NET/TSS.Net/CryptoLib.cs there is a compiler switch `#if TSS_USE_BCRYPT` which enables the usage of BCrypt and the `linux-arm` assembly in the NuGet package was compiled without it.  

BUT when i compile against `linux-arm64` I do not get that assembly, but some other assembly (`linux-musl-x64`?) which has BCrypt enabled. I then tried manually copying the `linux-arm` assembly which resulted in a `System.BadImageFormatException`.

Is there a way to fully use the current library with `linux-arm64`?

**Comment by chrfin** [comment]
I tried compiling it for `linux-arm64` and that seems to work. May you can include such a build in the next NuGet package?

**Comment by amarochk** [comment]
Yes, the current project settings will be used for the next nuget package drop.
