### ISSUE TITLE
TSS.CPP - Uninitialized values used in AUTH_SESSION

### ISSUE THREAD

**Issue by idlerun** [microsoft/TSS.MSR#75]
The default constructor for `AUTH_SESSION` (used by `PWAP()`) leaves uninitialized values.
https://github.com/microsoft/TSS.MSR/blob/master/TSS.CPP/include/Tss.h#L35

In my unlucky case the `SessionAttributes` random uninitialized value was being consumed in `Tpm2::PrepareParmEncryptionSessions` and triggering the `EncSessions = s` case (and further bad behavior)

Adding `SessionAttributes(0)` was sufficient to fix my particular error. Not submitting a PR as I don't know what all the sensible defaults should be for the other params.

**Comment by amarochk** [comment]
Thank you for reporting the issue! Though, it looks like the problem is not the default ctor not default-initializing the session attribute member, but rather it having been left public. The `AUTH_SESSION` class is supposed to be instantiated using either its `PWAP()` static method or one of the `Tpm2::StartAuthSession()` command overloads. So the fix will make the default ctor private.

BTW, how come that you have to manually construct this class?

**Comment by idlerun** [comment]
I actually hit this with a pretty minimal use case copying straight from the `RsaEncryptDecrypt()` example.

```
    TpmCpp::TpmTbsDevice device;
    device.Connect();
    TpmCpp::Tpm2 tpm(device);

    // We will make a key in the "null hierarchy".
    TPMT_PUBLIC primTempl(TPM_ALG_ID::SHA1,
        TPMA_OBJECT::decrypt | TPMA_OBJECT::userWithAuth | TPMA_OBJECT::sensitiveDataOrigin,
        null,  // No policy
        TPMS_RSA_PARMS(null, TPMS_SCHEME_OAEP(TPM_ALG_ID::SHA1), 2048, 65537),
        TPM2B_PUBLIC_KEY_RSA());

    // Create the key
    auto storagePrimary = tpm.CreatePrimary(TPM_RH_NULL, null, primTempl, null, null);
```

I get an error on the last line. The error is from `ParamXcrypt`, but it actually traces back to being caused by the invalid `SessionAttributes`. The session was created automatically here:

https://github.com/microsoft/TSS.MSR/blob/master/TSS.CPP/Src/Tpm2.cpp#L288

**Comment by idlerun** [comment]
Modifying PWAP() to clear that value also resolves my particular problem

```
        static AUTH_SESSION PWAP()
        {
            AUTH_SESSION s;
            s.handle = TPM_RH::PW;
            s.SessionAttributes = 0;
            return s;
        }
```

**Comment by amarochk** [comment]
Ah, I see. The bug was that the placeholder was used by the command dispatcher to check the session attributes, even though they do not make sense for password sessions. I'll commit the fix shortly.

**Comment by idlerun** [comment]
Fantastic! thanks for the quick fix
