### ISSUE TITLE
Machine Identification example

### ISSUE THREAD

**Issue by vslynko** [microsoft/TSS.MSR#77]
Hello,
I've looked through the .NET examples for the way, how to create a unique machine ID without success. Would anyone point me to a correct place, please?

Sorry for a newbie question, and thanks for help.

**Comment by amarochk** [comment]
Hi Vadim,

TSS.Net is just an interface to a TPM 2.0 device, and there is no function for machine ID generation in the TPM API, as a machine ID would normally capture information about multiple hardware (and sometimes firm- and software) components comprising the given platform.

If you, however, want to uniquely identify the TPM 2.0 device on your platform, then the public part of any **primary** asymmetric key in the endorsement hierarchy would do the trick. Such a key created by the TPM2_CreatePrimary() command from the same template (TPMT_PUBLIC structure) will always be the same on the same TPM and different on any other TPM.

Many TPMs are shipped or provisioned with the special Endorsement Key (EK) that comes with a cert and serves exactly this purpose (unique identification of the TPM device), and most platforms follow [TCG EK Credential Profile](https://trustedcomputinggroup.org/wp-content/uploads/Credential_Profile_EK_V2.0_R14_published.pdf) specification wrt. EK management.

-Andrey
