### ISSUE TITLE
Nuspec file includes deprecated 'licenseUrl' metadata

### ISSUE THREAD

**Issue by Werner-Prbk** [microsoft/TSS.MSR#78]
Please update nuspec file and replace deprecated 'licenseUrl' with 'license' metadata as recommended in the Microsoft docs https://docs.microsoft.com/en-us/nuget/reference/nuspec#licenseurl

**Comment by amarochk** [comment]
Hi Werner,

At the time of the nuget's next revision release the metadata enforced by Microsoft's internal signing infrastructure will be used.
