### ISSUE TITLE
TPM ERROR {VALUE} in RSA_Encrypt and RSA_Decrypt

### ISSUE THREAD

**Issue by eceunlu** [microsoft/TSS.MSR#79]
I'm trying to encrypt and decrypt in two diferent points A and B in my system, by first creating a key pair at A and sending that key pair's public key's unique to  B to create another key to encrypt my data with the intent of sending that encrpted data back. However when I send the encrypted data back that was created in B I seem to not be able to decrypt it and get this error provided down below instead.

Here is how I tryed to do this in code form:

/////////////////////////////////////////////////////////////

Creation of the original pair:

        TPMS_ENC_SCHEME_OAEP scheme = new TPMS_ENC_SCHEME_OAEP(TPM_ALG_ID.SHA256);

        TPMT_PUBLIC rsaEkTemplate = new TPMT_PUBLIC(TPM_ALG_ID.SHA256,
                new TPMA_OBJECT(TPMA_OBJECT.sensitiveDataOrigin,
                        TPMA_OBJECT.userWithAuth, TPMA_OBJECT.decrypt),
                null,
                new TPMS_RSA_PARMS(new TPMT_SYM_DEF_OBJECT(TPM_ALG_ID.NULL,  0, TPM_ALG_ID.NULL), scheme, 2048, 0),
                new TPM2B_PUBLIC_KEY_RSA());

        CreatePrimaryResponse rsaEk = tpm.CreatePrimary(TPM_HANDLE.from(TPM_RH.NULL),
                new TPMS_SENSITIVE_CREATE(), rsaEkTemplate, new byte[0], new TPMS_PCR_SELECTION[0]);
        //Key generation end

        //handler
        TPM_HANDLE keyHandle = rsaEk.handle;
        //handler end

        //BYTE[] TO SEND THE KEY
        byte[] ekBlobToSend = rsaEk.toBytes();

/////////////////////////////////////////////////////////////

Sending of the Blob to B at A:

            dos = new DataOutputStream(socket.getOutputStream());
            dos.write(ekBlobToSend, 0, ekBlobToSend.length);

/////////////////////////////////////////////////////////////

Getting the blob at B:

            bis = new BufferedInputStream(socket.getInputStream());
            dis = new DataInputStream(bis);

            //TAKE THE SENT DATA IN BYTE ARRAY FORM

            byte[] real = null;
            byte[] data = new byte[1000];
            int count = dis.read(data);
            real =new byte[count+1];
            for(int i=1;i<=count;i++)
                real[i]=data[i];

/////////////////////////////////////////////////////////////

Creating the new key with original Public's unique at B:

TPMT_PUBLIC ekPubPart = TPM2B_PUBLIC.fromBytes(real).publicArea;

            TPMT_PUBLIC ekPub = new TPMT_PUBLIC(TPM_ALG_ID.SHA1, new TPMA_OBJECT(TPMA_OBJECT.sensitiveDataOrigin,
                    TPMA_OBJECT.userWithAuth, TPMA_OBJECT.decrypt), null,
                    new TPMS_RSA_PARMS(new TPMT_SYM_DEF_OBJECT(TPM_ALG_ID.NULL,  0, TPM_ALG_ID.NULL), scheme, 2048, 0),
                    ekPubPart.unique);

            CreatePrimaryResponse ekPubPrimaryResponse = tpm.CreatePrimary(TPM_HANDLE.from(TPM_RH.NULL),
                    new TPMS_SENSITIVE_CREATE(), ekPub, new byte[0], new TPMS_PCR_SELECTION[0]);

/////////////////////////////////////////////////////////////

Encryption with the new key with original Public's unique at B:

byte[] dataToEncrypt=messageToServer.getBytes(StandardCharsets.UTF_8);
                    byte [] encryptedDataByteArray =tpm.RSA_Encrypt(ekPubPrimaryResponse.handle,dataToEncrypt,scheme,null);
                    String encryptedDataInBase64String = Base64.getEncoder().encodeToString(encryptedDataByteArray);

/////////////////////////////////////////////////////////////

Sending of the encrpted data to A at B:

dos.writeUTF(encryptedDataInBase64String);

/////////////////////////////////////////////////////////////

Decryption with the original Public key at B:

                    byte[] mydata = Base64.getDecoder().decode(messageFromClient);
                    byte[] decryptedData = tpm.RSA_Decrypt(keyHandle, mydata, scheme, null);
                    String decryptedDataString = new String(decryptedData, StandardCharsets.UTF_8);

/////////////////////////////////////////////////////////////

End of codes.

Here is the error itself:

TPM ERROR: {VALUE}
Exception in thread "main" tss.TpmException: TPM Exception: {VALUE}
	at tss.TpmBase.DispatchCommand(TpmBase.java:370)
	at tss.Tpm.RSA_Encrypt(Tpm.java:444)
	at server_client_working.Client.<init>(Client.java:89)
	at server_client_working.Client.main(Client.java:110)

**Comment by DavidWooten** [comment]
You cannot have two different TPMs create the same key. The key generation process uses TPM-specific, secret seeds. If the same public data caused all TPMs to produce the same secrets, then there would be no secrets.

 

If you want two TPMs to have the same keys, you need to create the key at TPM A and duplicate it to TPM B. Alternatively, you can create the keys external to the both TPMs and import them into TPM A and B.

 

David Wooten

**Comment by eceunlu** [comment]
First of all thank you for your short notice. For another method that I used, which is to use the data blob sent for encryption in TPMT_PUBLIC form which looks something like this:

            TPMT_PUBLIC ekPubPart = TPM2B_PUBLIC.fromBytes(real).publicArea;

And use its "encrypt()" method to encrypt:

ekPubPart.encrypt(dataToEncrypt,"dummy");

Then send the encypted data back in the end use RSA_Decrypt to decrypt will not work as well. How can I import or duplicate and existing key to another TPM?

**Comment by DavidWooten** [comment]
I am not familiar with the TSS or how it handles duplication. I hope someone else is willing to step in and help.

 

BTW, duplication is described in Part 1 of the TPM specification (Clause 23.3 “Duplication”).

**Comment by eceunlu** [comment]
Thank you, I will check it out.
