### ISSUE TITLE
Generate CSR

### ISSUE THREAD

**Issue by ariolaclint** [microsoft/TSS.MSR#81]
How to generate CSR in TPM?

**Comment by amarochk** [comment]
TPM does not support this functionality. The only PKI related command is TPM2_CertifyX509() that completes and signs a partially constructed certificate and is only available in TPM 2.0 revisions 1.59 and above.

**Comment by ariolaclint** [comment]
@amarochk  Thank you for your quick response. Can we import existing private key into TPM and used to sign data?
