### ISSUE TITLE
Import Private key 

### ISSUE THREAD

**Issue by ariolaclint** [microsoft/TSS.MSR#82]
Can we import existing private key into TPM and used to sign data?
Any reference in the library implementing this use case, many thanks.

**Comment by amarochk** [comment]
Yes, you need to pack your external key into the data structures defined by the TPM 2.0 specification for key duplication, i.e. make it look as if they are the result of the TPM2_Duplicate() command used for plain text duplication. Then you can use them with the TPM2_Import() command.

See the [ExternalKeyImportSample](https://github.com/microsoft/TSS.MSR/blob/f0afe4e9e140b892fe41aff25501b58711856b22/Tpm2Tester/TestSuite/Sample-KeyImport.cs#L83) sample. This method allows importing RSA keys. If you need to import an ECC key, you'll have to add the appropriate logic into the TssObject.CreateSensitiveComposite() method. 

The other way to use an external key in the TPM is the TPM2_LoadExternal() command. See the [LoadExternalFullRsaKeySample](https://github.com/microsoft/TSS.MSR/blob/f0afe4e9e140b892fe41aff25501b58711856b22/Tpm2Tester/TestSuite/Sample-KeyImport.cs#L144) sample.
